version: "3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qJiw03K2zwJD
      - MYSQL_DATABASE=webshop
    ports:
      - 4000:3306
    expose:
      - 3306
    volumes:
      - "/Users/jart/tmp:/var/lib/mysql"

  web:
    image: jarltuxen/webshopmini
    restart: on-failure
    depends_on:
      - db
    ports:
      - 9090:9090

